apiVersion: v1
kind: ServiceAccount
metadata:
  name: setmaxproc-webhook
  namespace: setmaxproc-webhook
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: setmaxproc-webhook
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["admissionregistration.k8s.io"]
  resources: ["mutatingadmissionwebhooks"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: setmaxproc-webhook
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: setmaxproc-webhook
subjects:
- kind: ServiceAccount
  name: setmaxproc-webhook
  namespace: setmaxproc-webhook 