apiVersion: admissionregistration.k8s.io/v1
kind: MutatingAdmissionWebhook
metadata:
  name: setmaxproc-webhook
spec:
  webhooks:
  - name: setmaxproc.webhook.io
    clientConfig:
      service:
        name: setmaxproc-webhook
        namespace: setmaxproc-webhook
        path: "/mutate"
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0t  # This will be replaced by the actual CA bundle
    rules:
    - operations: ["CREATE", "UPDATE"]
      apiGroups: [""]
      apiVersions: ["v1"]
      resources: ["pods"]
    namespaceSelector:
      matchExpressions:
      - key: name
        operator: NotIn
        values: ["kube-system", "kube-public", "setmaxproc-webhook"]
    objectSelector:
      matchExpressions:
      - key: setmaxproc.webhook/skip
        operator: DoesNotExist
    admissionReviewVersions: ["v1", "v1beta1"]
    sideEffects: None
    failurePolicy: Fail 