apiVersion: v1
kind: Pod
metadata:
  name: go-app-high-cpu
  namespace: default
  labels:
    app: go-test
spec:
  containers:
  - name: go-app
    image: golang:1.21
    command: ["sleep", "infinity"]
    resources:
      requests:
        cpu: "1000m"
        memory: "512Mi"
      limits:
        cpu: "2500m"  # This should result in GOMAXPROCS=3 (2.5 CPU, rounded up to 3)
        memory: "1Gi" 