apiVersion: v1
kind: Pod
metadata:
  name: go-app-skip-webhook
  namespace: default
  labels:
    app: go-test
  annotations:
    setmaxproc.webhook/skip: "true"  # This annotation will skip the webhook
spec:
  containers:
  - name: go-app
    image: golang:1.21
    command: ["sleep", "infinity"]
    env:
    - name: GOMAXPROCS
      value: "4"  # Manually set GOMAXPROCS, webhook won't override
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "1000m"
        memory: "256Mi" 