apiVersion: v1
kind: Pod
metadata:
  name: go-app-with-limits
  namespace: default
  labels:
    app: go-test
spec:
  containers:
  - name: go-app
    image: golang:1.21
    command: ["sleep", "infinity"]
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "500m"  # This should result in GOMAXPROCS=1 (500m = 0.5 CPU, rounded up to 1)
        memory: "256Mi" 