apiVersion: v1
kind: Pod
metadata:
  name: go-app-multi-container
  namespace: default
  labels:
    app: go-test
spec:
  containers:
  - name: go-app-1
    image: golang:1.21
    command: ["sleep", "infinity"]
    # No resource limits - will use: max(system_cpus / 250, 2)
  - name: go-app-2
    image: golang:1.21
    command: ["sleep", "infinity"]
    # No resource limits - will use: max(system_cpus / 250, 2)
  - name: go-app-3
    image: golang:1.21
    command: ["sleep", "infinity"]
    # No resource limits - will use: max(system_cpus / 250, 2) 